
[package]
name = "c_borrow_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
clang-sys = "1.2"
clang = "1.0"
regex = "1.10.6"
serde_json = {version = "1.0.128", features = ["preserve_order"]}
nix = { version = "0.29.0", features = ["process"] }
